FROM python:3.14-alpine

WORKDIR /app

ENV PYTHONPATH .
ENV PYTHONBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apk add --no-cache poetry

COPY pyproject.toml ./poetry.lock .

RUN poetry install --no-root

COPY ./src ./src

EXPOSE 8000

CMD poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000

#CMD tail -f /dev/null

